### ISSUE TITLE
Software for This?

### ISSUE THREAD

**Issue by crashangelbr** [dikonov/Universal-Dictionary-of-Concepts#2]
hello friend, I am studying UNL and I would like to know where I find software that works as a tag for the input text ...
thankful

**Comment by dikonov** [comment]
Hi!
 
Your question is not quite clear, but I think that you mean an «encoder» — sw that produces UNL graphs from natural language text.
There are several of them, all developed by different groups and using different principles. I included some links to such systems in the UNLDC git page. 
 
I took part in the making of the Russian and English encoder.  You can try (an older version) at www.unl.ru.  The problem is that this encoder is a module of a very old and complex proprietary (not commercial but academic) system ETAP-3. It cannot function without the base system and straight re-creating it takes a lot of man-years. The encoder desperately needs a state of the art word sense disambiguation part, but there was no support for making it at the time. 
Another link is  http://proling.iitp.ru/etap4download  It should include UNL enco-deco options.
 
 
The Spanish group made their own encoder for Spanish, but later they turned to commerce and all further development is under stupid NDA.
 
Now there are many open-source taggers, parsers, etc, it becomes possible to create a free as freedom encoder and decoder, if there will be volunteers with good coding skills to do it.
 
Sorry for delayed reply.
 
>hello friend, I am studying UNL and I would like to know where I find software that works as a tag for the input text ...
>thankful
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Vyacheslav Dikonov

**Comment by crashangelbr** [comment]
Hello,

I'm doing a chat that uses Pos-Tagger to do Parsing and Dependency Analysis of the input text ... I realized that UNL can list me a way to understand the concepts that make up the universe of the input text .... I I'm thinking of recording these files in some database ... but for that I would like to know if the functions of the UNL analyzer checks word by word and queries in csv files in a crude way ... Type a word without distinction ... If so, it would be easier to guess the meaning of the input attempt ... Now if there are different words that the analyzer functions know how to check, you would need to use an external analyzer ... Do any of the ones you have informed work for this type of occasion?

**Comment by dikonov** [comment]
The csv files are just a simplest possible format to dump and store the dictionary data. It is actually taken from a French system named «Ariane». Every system uses its own unique format, so it makes no sense to design a single DB to fit all. Naturally, for heavy use you will need to put the data into your own database.
 
My ETAP-based UNL encoder builds a syntactic dependency tree of a sentence and uses it as an input to make UNL graph. Words are partially disambiguated by the syntactic parser already, but it is a "coarse grain" level. Further, the UNL enconverter must select one of several "fine grain" alternatives. In ETAP it uses rules to evaluate the context. This mechanism actually needs improvement.
 
The desktop version also has an option to interactively select syntax relations and the UWs, if the system fails to choose right. Anyway, the original UNL approach is to generate (or even wright manually) UNL code once and generate text in many languages, knowing that the resulting NL text will be correct. 
>Вторник, 21 июля 2020, 16:23 +03:00 от Crash Angel <notifications@github.com>:
> 
> 
>Hello,
>I'm doing a chat that uses Pos-Tagger to do Parsing and Dependency Analysis of the input text ... I realized that UNL can list me a way to understand the concepts that make up the universe of the input text .... I I'm thinking of recording these files in some database ... but for that I would like to know if the functions of the UNL analyzer checks word by word and queries in csv files in a crude way ... Type a word without distinction ... If so, it would be easier to guess the meaning of the input attempt ... Now if there are different words that the analyzer functions know how to check, you would need to use an external analyzer ... Do any of the ones you have informed work for this type of occasion?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Vyacheslav Dikonov
